backend:
  name: github
  repo: peraures/blog
  branch: main
  site_domain: https://peraures.pages.dev
  base_url: https://peraures.pages.dev
  auth_endpoint: api/auth

  
  client_id: ${GITHUB_CLIENT_ID}
  client_secret: ${GITHUB_CLIENT_SECRET}

media_folder: ""
public_folder: ""

collections:
  - name: "posts"
    label: "블로그 글"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: "제목", name: "title", widget: "string", picker_utc: "false" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
      - { label: "이미지", name: "image", widget: "image" }
      - 
        label: "태그"
        name: "tags"
        widget: "list"
        multiple: true
        default: []
        fields:
          - { label: "태그", name: "tag", widget: "string" }
