backend:
  name: github
  repo: peraures/blog
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "posts"
    label: "블로그 글"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"  # index.md로 글이 저장될 거야
    media_folder: ""         # 이미지 저장 경로
    public_folder: ""        # CMS가 이미지 경로를 상대적으로 처리할 수 있게
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
      - { label: "이미지", name: "image", widget: "image" }
      - { label: "태그", name: "tags", widget: "list", field: { widget: "string" } }
