backend:
  name: github
  repo: peraures/blog
  branch: main
  site_domain: https://peraures.pages.dev
  base_url: https://peraures.pages.dev
  auth_endpoint: api/auth

  
  client_id: ${GITHUB_CLIENT_ID}
  client_secret: ${GITHUB_CLIENT_SECRET}

media_folder: ""
public_folder: ""

collections:
  - name: "posts"
    label: "블로그 글"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: "content/post"
    public_folder: ""
    fields:
      - { label: "이미지", name: "image", widget: "image" }
      - { label: "제목", name: "title", widget: "string"}
      - { label: "설명", name: "description", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime", picker_utc: false, format: "YYYY-MM-DDTHH:mm:ssZZ" }
      - 
        label: "카테고리"
        name: "categories"
        widget: "list"
        default: []
        hint: "카테고리를 추가하세요 (예: 음향, 전자음악, 문제)"
      - 
        label: "태그"
        name: "tags"
        widget: "list"
        multiple: true
        default: []
      - { label: "본문", name: "body", widget: "markdown" }

     