backend:
  name: github
  repo: peraures/blog
  branch: main
  site_domain: https://peraures.pages.dev
  base_url: https://peraures.pages.dev
  auth_endpoint: api/auth

  
  client_id: ${GITHUB_CLIENT_ID}
  client_secret: ${GITHUB_CLIENT_SECRET}

media_folder: ""
public_folder: ""

collections:
  - name: "posts"
    label: "블로그 글"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    media_folder: "{{slug}}"
    public_folder: "/post/{{slug}}"
    fields:
      - { label: "이미지", name: "image", widget: "image" }
      - { label: "제목", name: "title", widget: "string"}
      - { label: "설명", name: "description", widget: "string" }
      - { label: "날짜", name: "date", widget: "datetime", picker_utc: false, format: "YYYY-MM-DDTHH:mm:ssZZ" }
      - 
        label: "카테고리"
        name: "categories"
        widget: "relation"
        collection: "categories_list" # 참조할 컬렉션 이름
        search_fields: ["title"] # 검색할 필드
        value_field: "title" # 저장할 값
        display_fields: ["title"] # 표시할 필드
        multiple: true # 다중 선택 가능
        hint: "카테고리를 선택하세요"
      - 
        label: "태그"
        name: "tags"
        widget: "list"
        multiple: true
        default: []
      - { label: "본문", name: "body", widget: "markdown" }
      - 
        label: "마지막 수정"
        name: "lastmod"
        widget: "datetime"
        required: false
        default: []
        format: "YYYY-MM-DDTHH:mm:ssZZ"
        hint: "이 필드는 자동으로 현재 날짜와 시간으로 설정됩니다."

  - name: "categories_list" # 카테고리 컬렉션 추가
    label: "카테고리"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/_index"
    fields:
      - { label: "제목", name: "title", widget: "string" }